magis:
  default_view_mode: direct
  # This option will be available in future

  #template_path: '%kernel.project_dir%/templates'
  # template directory
  # default: '%kernel.project_dir%/templates'

  services:

    #- {<alias>:<service_class_or_alias>}
    # Use this to inject services as parameters