parameters:
  # nothing

services:
  pjpawel\Magis\ViewDispatcherService:
    arguments: ['direct', '', []]
    autowire: true

  magis.view:
    alias: pjpawel\Magis\ViewDispatcherService
    public: true